name: lyxa_live
description: "A new Flutter project."
publish_to: 'none' 


version: 0.0.1


environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.4.5
  firebase_storage: ^12.3.5
  file_picker: ^8.1.3
  cached_network_image: ^3.4.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  get_it: ^7.6.0
  injectable: ^2.2.0
  flutter_svg: ^2.0.0
  carousel_slider: ^5.0.0
  image_cropper: ^8.0.2
  flutter_image_compress: ^2.3.0
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway_regular.ttf
        - asset: assets/fonts/raleway_medium.ttf
          weight: 600
    - family: Dynalight
      fonts:
        - asset: assets/fonts/dynalight_regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 600
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/el_messiri_regular.ttf
        - asset: assets/fonts/el_messiri_semi_bold.ttf
          weight: 600


