// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPRZE3LZt1LfX09hA-EFnn_BEQ2qKB3ww',
    appId: '1:514084610800:web:af188c16418f48921b1835',
    messagingSenderId: '514084610800',
    projectId: 'lyxa-live-app',
    authDomain: 'lyxa-live-app.firebaseapp.com',
    storageBucket: 'lyxa-live-app.firebasestorage.app',
    measurementId: 'G-V36E7251L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNkXuh_Qx2_2FvZOK55BUtUHVzipdrx28',
    appId: '1:514084610800:android:de9d21170f30ccc21b1835',
    messagingSenderId: '514084610800',
    projectId: 'lyxa-live-app',
    storageBucket: 'lyxa-live-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi_NldGbyYclB_XnCQpw6LQqMorBQnluU',
    appId: '1:514084610800:ios:dec4d8fa982402c51b1835',
    messagingSenderId: '514084610800',
    projectId: 'lyxa-live-app',
    storageBucket: 'lyxa-live-app.firebasestorage.app',
    iosBundleId: 'novalogics.flutter.lyxaLive',
  );
}
